"""The single-qubit Clifford group (24 elements) for randomized benchmarking.

Generated by closure under the generators {H, S} (which generate the whole 1-qubit Clifford
group), with elements compared up to a global phase. Provides the group, a canonicaliser, and
an inverse lookup so an RB sequence can be capped with the Clifford that ideally returns the
state to |0>.
"""
from __future__ import annotations

import numpy as np

from .backend import H, I2, S, X, Y, Z


def _canonical(U: np.ndarray) -> tuple:
    """A phase-invariant, float-robust key for a single-qubit Clifford.

    Fingerprint the Clifford by HOW it conjugates the Paulis: U P U^dag is a signed Pauli for
    each P in {X,Y,Z}, i.e. a signed permutation of the axes (the 24 octahedral rotations).
    This is exactly invariant to global phase (U P U^dag is unchanged by e^{i.phi}) and the
    entries are ±1/0, so it has none of the tie/rounding fragility of picking matrix entries.
    """
    paulis = (X, Y, Z)
    key = []
    for P in paulis:
        Q = U @ P @ U.conj().T
        for k, Pp in enumerate(paulis):
            c = np.trace(Q @ Pp).real / 2.0     # ±1 if Q = ±Pp, else 0
            if abs(c) > 0.5:
                key.append((k, 1 if c > 0 else -1))
                break
    return tuple(key)


def generate_clifford_group() -> list[np.ndarray]:
    """All 24 single-qubit Cliffords as 2x2 unitaries (canonical global phase)."""
    gens = [H, S]
    seen: dict[tuple, np.ndarray] = {_canonical(I2): I2.copy()}
    frontier = [I2.copy()]
    while frontier:
        nxt = []
        for U in frontier:
            for g in gens:
                V = g @ U
                key = _canonical(V)
                if key not in seen:
                    seen[key] = V
                    nxt.append(V)
        frontier = nxt
    return list(seen.values())


class CliffordGroup:
    def __init__(self):
        self.elements = generate_clifford_group()
        self._index = {_canonical(U): i for i, U in enumerate(self.elements)}
        assert len(self.elements) == 24, f"expected 24 Cliffords, got {len(self.elements)}"

    def __len__(self) -> int:
        return len(self.elements)

    def random_indices(self, m: int, rng: np.random.Generator) -> np.ndarray:
        return rng.integers(0, len(self.elements), size=m)

    def inverse_of_product(self, U_product: np.ndarray) -> np.ndarray:
        """The group element that (ideally) inverts the accumulated unitary U_product."""
        inv = U_product.conj().T
        key = self._index.get(_canonical(inv))
        if key is None:
            raise KeyError("product inverse is not a Clifford (numerical/closure error)")
        return self.elements[key]
